# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0
    #resource_class: medium
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean build 
      - run: ./gradlew clusterfuzzAssemble --stacktrace
      - persist_to_workspace:
          root: build
          paths:
            - ./libs
            - ./clusterfuzz/assemble
  
  security:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0
    #resource_class: medium
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean dependencyCheckAnalyze

  clusterfuzz:
    docker:
      - image: cifuzz/jazzer
#    resource_class: medium
    working_directory: ~/fuzz
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/workspace
      - run: wget https://github.com/CodeIntelligenceTesting/jazzer/releases/download/v0.12.0/jazzer-linux-x86_64.tar.gz && tar -xvzf *.gz
      - run: chmod +x jazzer
      - run: ls -R ~/workspace
      - run: cp ~/workspace/clusterfuzz/assemble/* .
      - run: ls -altr
#      - run: ./jazzer --target_class=com.fizzpod.gradle.plugins.clusterfuzz.ClusterfuzzPluginExtensionFuzzTest
      - run: ./jazzer --cp=commons-io-2.11.0.jar:gradle-api-7.5.1.jar:gradle-installation-beacon-7.5.1.jar:groovy-3.0.10.jar:groovy-ant-3.0.10.jar:groovy-astbuilder-3.0.10.jar:groovy-console-3.0.10.jar:groovy-datetime-3.0.10.jar:groovy-dateutil-3.0.10.jar:groovy-groovydoc-3.0.10.jar:groovy-json-3.0.10.jar:groovy-nio-3.0.10.jar:groovy-sql-3.0.10.jar:groovy-templates-3.0.10.jar:groovy-test-3.0.10.jar:groovy-xml-3.0.10.jar:javaparser-core-3.17.0.jar:jazzer-api-0.12.0.jar:kotlin-reflect-1.6.21.jar:kotlin-stdlib-1.6.21.jar:kotlin-stdlib-common-1.6.21.jar:kotlin-stdlib-jdk7-1.6.21.jar:kotlin-stdlib-jdk8-1.6.21.jar --target_class=com.fizzpod.gradle.plugins.clusterfuzz.ClusterfuzzPluginExtensionFuzzTest
#      - run: bash run.sh
#      - run: ls -altr && ./run.sh
#      - run: cat /etc/os-release
#      - run: uname -r
#      - run: whoami
#      - run: printenv
#      - run: cd ~/workspace && ls -R
#      - run: ls -altr / 
#      - run: ls -altr /usr/bin
#      - run: cd /fuzzing && ls -R
#      - run: cd / && ls -R
#      - run: cd /fuzz && ./jazzer
      #find / -name 'jazzer'
    
  publish:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      # TODO re-enable these steps
#      - run: ./gradlew clean verifyRelease createRelease
#      - run: ./gradlew clean build
#      - run: ./gradlew publish
#      - run: ./gradlew publishPlugins

workflows:
  build:
    jobs:
      - build:
          context: boxhead-builds
      - clusterfuzz:
          context: boxhead-builds
          requires:
            - build

      - security:
          context: boxhead-builds
          requires:
            - build
          filters:
            branches:
              only: /^release.*$/
      - publish:
          context: boxhead-builds
          requires:
            - build
          filters:
            branches:
            #TODO change me to main
              only: donotrun