# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ls -altR
      - run: ./gradlew clean build clusterfuzz
      - persist_to_workspace:
          root: build
          paths:
            - ./libs
            - ./clusterfuzz/assemble
  
  security:
    docker:
      # specify the version you desire here
      - image: boxheed/openjdk-17-nvd-cve-db:latest
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean dependencyCheckAnalyze

  security-2:
    docker:
      - image: cimg/go:1.20-node
    steps:
      - checkout
      - run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - run: echo "Hello World"

  clusterfuzz:
    docker:
      - image: gcr.io/oss-fuzz-base/base-builder-jvm
    working_directory: ~/fuzz
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/workspace
      - run: cp -r ~/workspace/clusterfuzz/assemble/* .
      - run: ls -altR
      - run: bash ./bin/run.sh
      - run: ls -altR
      - store_artifacts: 
          path: ~/fuzz
  
  release:
    docker:
      # specify the version you desire here
      - image: boxheed/openjdk-17-nvd-cve-db:latest
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew createRelease
      - run: git push --tags
   
  publish:
    docker:
      # specify the version you desire here
      - image: boxheed/openjdk-17-nvd-cve-db:latest
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew build publish publishPlugins githubRelease

workflows:
  build:
    jobs:
      - build:
          context: boxhead-builds
      - clusterfuzz:
          context: boxhead-builds
          requires:
            - build
          filters:
            branches:
              only: /^develop.*$/
      - security:
          context: boxhead-builds
      - security-2:
          context: boxhead-builds
      - release:
          context: boxhead-builds
          requires:
            - build
            - security
          filters:
            branches:
              only: /^(?:main|master)$/
      - publish:
          context: boxhead-builds
          filters:
            # only act on version tags
            branches:
              ignore: /.*/
            tags:
              only: /^release-\d+\.\d+\.\d+$/
