# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ls -altR
      - run: ./gradlew clean build clusterfuzz
      - persist_to_workspace:
          root: build
          paths:
            - ./libs
            - ./clusterfuzz/assemble
  
  security:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean dependencyCheckAnalyze

  clusterfuzz:
    docker:
      - image: gcr.io/oss-fuzz-base/base-builder-jvm
    working_directory: ~/fuzz
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/workspace
      - run: cp -r ~/workspace/clusterfuzz/assemble/* .
      - run: ls -altR
      - run: bash ./bin/run.sh
      - run: ls -altR
      - store_artifacts: 
          path: ~/fuzz

    
  publish:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean verifyRelease createRelease
      - run: ./gradlew clean build
      - run: ./gradlew publish
      - run: ./gradlew publishPlugins

workflows:
  build:
    jobs:
      - build:
          context: boxhead-builds
      - clusterfuzz:
          context: boxhead-builds
          requires:
            - build
          filters:
            branches:
              only: /^develop.*$/
      - security:
          context: boxhead-builds
          requires:
            - build
          filters:
            branches:
              only: /^release.*$/
      - publish:
          context: boxhead-builds
          requires:
            - build
          filters:
            branches:
              only: main